services:
  express-app:
    image: smlltt797/express-app-docker-mooc-sl:latest
    container_name: express-app
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=latest'      # Tell WUD to watch the 'latest' tag
      - 'wud.watch.digest=true'       # Track by digest (hash) instead of version
      - 'wud.trigger.include=docker.auto'
    ports:
      - "8080:8080"

  whatsupdocker:
    image: getwud/wud
    container_name: wud
    environment:
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      - WUD_TRIGGER_DOCKER_AUTO_PRUNE=true
      - WUD_PORT=3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3000"